services:
  auth-service:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      SECRET: "wefujrogueru9gr4580"
      CONFIG_PATH: "/app/config.yaml"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"